In [1]:
import numpy as np
from statistics import mode

In statistics, a population is the pool of individuals from which a statistical sample is drawn for a study. 

# Making random population

In [2]:
population1 = np.random.randint(10,20,50)# to genarate 50 random integer inside the dataset in the range 10 to 20
population2 = np.random.binomial(10,0.5,10000)# result of flipping a coin 10 times, tested 10000 times, with prob = 0.5.

In [3]:
population1

array([11, 19, 17, 15, 14, 15, 11, 12, 17, 15, 14, 10, 17, 10, 13, 14, 17,
       10, 13, 19, 18, 17, 11, 16, 18, 19, 17, 12, 18, 16, 19, 17, 10, 13,
       12, 16, 16, 19, 19, 11, 19, 15, 10, 11, 12, 15, 16, 11, 19, 16])

In [4]:
population2

array([2, 6, 6, ..., 7, 4, 5])

In [5]:
len(population2)

10000

# Mean Median Mode

In [6]:
#mean
np.mean(population1)

14.82

In [7]:
#median
np.median(population1)

15.0

In [8]:
#mode
mode(population1)

19

# Sampling

In [9]:
# Taking 3 sample of size 10 from the population
sample1 = np.random.choice(population1,10)
sample2 = np.random.choice(population1,10)
sample3 = np.random.choice(population1,10)

In [10]:
print(sample1)
print(30*"=")
print(sample2)
print(30*"=")
print(sample3)
print(30*"=")

[14 12 19 14 10 17 18 14 16 12]
[15 11 19 17 17 17 19 15 14 12]
[14 16 14 11 16 17 12 16 12 18]


In [11]:
print(f"mean of the sample1 : {np.mean(sample1)}")
print(f"median of the sample1 : {np.median(sample1)}")
print(f"mode of the sample1 : {mode(sample1)}")

mean of the sample1 : 14.6
median of the sample1 : 14.0
mode of the sample1 : 14
