# Numpy is important because:
    NumPy can be used to perform a wide variety of mathematical operations on arrays/matrix.
    System can't understand image/audio/video/text
    System needs all information in the form of arrays and matrix 
    Using Numpy the convertion of them into array/matrix is possible

In [1]:
import numpy as np 

# Converting List into an 1D Array

In [2]:
l = [1,2,3,4,4]

In [3]:
type(l)

list

In [4]:
a = np.array(l)

In [5]:
type(a)

numpy.ndarray

In [6]:
a

array([1, 2, 3, 4, 4])

# Making 2D Array using Lists and 1 Square Brackets

In [7]:
a1 = np.array([[1,2,3] , [3,4,5]])
a1

array([[1, 2, 3],
       [3, 4, 5]])

# Making 3D Array using Lists and 2 Square Brackets

In [8]:
a2 = np.array([[[1,2,3] , [4,.5,6]]])

In [9]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [10]:
a

array([1, 2, 3, 4, 4])

# Finding Dimensions of Arrays Created

In [11]:
a.ndim

1

In [12]:
a1.ndim


2

In [13]:
a2.ndim

3

In [14]:
a3 = np.array([[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]]])

In [15]:
a3

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [16]:
a3.ndim

3

# Using asarray to convert list into array

In [17]:
l = [1,2,3,4]

In [18]:
a = np.asarray(l)
type(a)

numpy.ndarray

# Using matrix to convert list into matrix

    Matrix have atleast 2 Dimension
    Array have atleast 3 Dimension
    
    Matrix ia a subset of array

In [19]:
m = np.matrix(l)
type(m)

numpy.matrix

# Using asanyarray

In [20]:
# asanyarray can be used to convert list into an array
np.asanyarray(l)

array([1, 2, 3, 4])

In [21]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [22]:
# But asanyarray will not convert a matrix into an array, because matrix is also a type of array
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

# Shallow Copying

In [23]:
print(a)
type(a)

[1 2 3 4]


numpy.ndarray

In [24]:
a1 = a 
type(a1)

numpy.ndarray

In [25]:
a[0] = 10

In [26]:
a

array([10,  2,  3,  4])

In [27]:
a1# both a and a1 are same because a1=a

array([10,  2,  3,  4])

In [28]:
a1[3] = 50

In [29]:
a1

array([10,  2,  3, 50])

In [30]:
a

array([10,  2,  3, 50])

**In shallow copying, changes in a1 is reflected in a**

# Deep Copying

In [31]:
a2 = np.copy(a)

In [32]:
a2

array([10,  2,  3, 50])

In [33]:
a2[2] = 30

In [34]:
a2

array([10,  2, 30, 50])

In [35]:
a

array([10,  2,  3, 50])

**In deep copying, changes in a2 is not reflected in a**

# Generating an array via fromfunction

In [36]:
np.fromfunction(lambda i,j : i==j , (3,4))
# Dimesion of it is 3*4 and wherever row number - column number-->  True is displayed, otherwise, its shown by False

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [37]:
# Generating array of dimension (2,3,2) using random numbers
np.random.rand(2,3,2)

array([[[0.44111187, 0.29729965],
        [0.21360349, 0.77558223],
        [0.64082018, 0.04221715]],

       [[0.88759585, 0.6729367 ],
        [0.23094186, 0.05361156],
        [0.45076414, 0.54862553]]])

In [38]:
# Generating array of dimension (2,3,2,2) using random numbers
np.random.rand(2,3,2,2)

array([[[[0.56797247, 0.55089578],
         [0.59893274, 0.93755632]],

        [[0.58490827, 0.32626968],
         [0.42534004, 0.82726739]],

        [[0.61147442, 0.38052196],
         [0.54956315, 0.58937583]]],


       [[[0.38931911, 0.38304663],
         [0.62078082, 0.8458981 ]],

        [[0.37426674, 0.10972701],
         [0.41350229, 0.2230668 ]],

        [[0.28060895, 0.68952186],
         [0.40622018, 0.50930732]]]])

In [39]:
np.random.rand(3,4,5)

array([[[0.01331053, 0.11211761, 0.57961422, 0.71958834, 0.53246972],
        [0.35375969, 0.48651467, 0.55810564, 0.29774713, 0.0232501 ],
        [0.78596991, 0.36665405, 0.33550827, 0.20637773, 0.84080768],
        [0.42799286, 0.85215007, 0.36498072, 0.01718468, 0.55171774]],

       [[0.57421738, 0.17258185, 0.6518394 , 0.46846219, 0.4157697 ],
        [0.49137763, 0.25588878, 0.32324054, 0.95138689, 0.08912799],
        [0.28758907, 0.59138179, 0.23738889, 0.62414364, 0.82682462],
        [0.042287  , 0.64434086, 0.41671035, 0.94847119, 0.85154287]],

       [[0.83900383, 0.50547221, 0.35924752, 0.81461643, 0.37850921],
        [0.47659932, 0.74244112, 0.85549081, 0.59989722, 0.04207079],
        [0.53327045, 0.84965688, 0.50509242, 0.44358517, 0.39205056],
        [0.33632004, 0.23778856, 0.68637776, 0.96487096, 0.06961032]]])

# Converting Array into Dataframe

In [40]:
d = np.random.randn(3,4)
d

array([[ 0.6902524 ,  0.17454857, -0.80833386,  1.30167134],
       [ 1.10935412, -0.50887602, -0.64854642,  2.55959236],
       [ 1.98852696, -1.58630656, -0.0695129 , -2.46239003]])

In [41]:
import pandas as pd
pd.DataFrame(d)

0         1         2         3
0  0.690252  0.174549 -0.808334  1.301671
1  1.109354 -0.508876 -0.648546  2.559592
2  1.988527 -1.586307 -0.069513 -2.462390

# Forming Integer Array

In [42]:
#Generating array having random integer values
d1=np.random.randint(0,10,(4,4,2))# Dataset having integers in range 0 to 10, dimension = 4*4*2
d1

array([[[4, 2],
        [5, 0],
        [4, 9],
        [0, 4]],

       [[8, 6],
        [9, 3],
        [7, 0],
        [1, 9]],

       [[0, 5],
        [3, 1],
        [7, 8],
        [8, 9]],

       [[6, 0],
        [7, 9],
        [3, 0],
        [2, 3]]])

# Changing dimension of existing array

    There are total 32 elements in d1, its dimention can be 16*2, 8*4, 32*1

In [43]:
d1.reshape(16,2)

array([[4, 2],
       [5, 0],
       [4, 9],
       [0, 4],
       [8, 6],
       [9, 3],
       [7, 0],
       [1, 9],
       [0, 5],
       [3, 1],
       [7, 8],
       [8, 9],
       [6, 0],
       [7, 9],
       [3, 0],
       [2, 3]])

In [44]:
d1.reshape(8,4)

array([[4, 2, 5, 0],
       [4, 9, 0, 4],
       [8, 6, 9, 3],
       [7, 0, 1, 9],
       [0, 5, 3, 1],
       [7, 8, 8, 9],
       [6, 0, 7, 9],
       [3, 0, 2, 3]])

In [45]:
d1.reshape(32,-421365981374)

array([[4],
       [2],
       [5],
       [0],
       [4],
       [9],
       [0],
       [4],
       [8],
       [6],
       [9],
       [3],
       [7],
       [0],
       [1],
       [9],
       [0],
       [5],
       [3],
       [1],
       [7],
       [8],
       [8],
       [9],
       [6],
       [0],
       [7],
       [9],
       [3],
       [0],
       [2],
       [3]])

In [46]:
pd.DataFrame(d1)

ValueError: Must pass 2-d input. shape=(4, 4, 2)

In [47]:
#Only 2D array can be converted into dataframe
d1=d1.reshape(8,4)

In [48]:
pd.DataFrame(d1)

0  1  2  3
0  4  2  5  0
1  4  9  0  4
2  8  6  9  3
3  7  0  1  9
4  0  5  3  1
5  7  8  8  9
6  6  0  7  9
7  3  0  2  3