# Generating inetgers in a particular range 

In [1]:
import numpy as np

In [2]:
range(10)# a generator function which gives range object, to generate numbers

range(0, 10)

In [3]:
list(range(10))# will give number list from 0 to 9

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(3 ,10))# will give number list from 3 to 9

[3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(3 ,10.5))

# Never use floating point elements while mentioning range

TypeError: 'float' object cannot be interpreted as an integer

# Generating Floating point numbers in a particular range

In [6]:
np.arange(10)
#arange is advanced version of range function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(.5 , 10)
#numbers from 0.5 to 10, with equal interval

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [8]:
np.arange(5 ,-4, -1)
# numbers 5 to -4(excluding -4) with equal interval of -1

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [9]:
np.arange(5 ,-4, -.5)
# numbers 5 to -4(excluding -4) with equal interval of -0.5

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [10]:
list(np.linspace(1,5,20,retstep=True))
# generates 20 datapoints in range 1 to 5

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

In [11]:
np.logspace(1,50,10)
# generates 10 log of datapoints(base -10) in range 1 to 50

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

# Generating Array having zeros

In [12]:
# Making a 1D array of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

# Generating array having ones

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [17]:
np.ones((3,4,2))*5

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

# Making Empty Array

In [18]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# Making Identity Matrix of dimension 4

In [19]:
a = np.eye(4)

In [20]:
a.shape

(4, 4)

In [21]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
a.size

16

In [23]:
a.ndim

2

# Make a matrix using random numbers

In [24]:
a1 = np.random.randn(3,4)

In [25]:
a1

array([[-1.11079282, -1.58488513,  1.83270074, -0.66310413],
       [ 0.11601061,  1.77481002, -0.98580459,  1.18884926],
       [ 1.67485449, -1.12107986,  0.71257819, -0.03732553]])

In [26]:
import pandas as pd 

In [27]:
pd.DataFrame(a1)

0         1         2         3
0 -1.110793 -1.584885  1.832701 -0.663104
1  0.116011  1.774810 -0.985805  1.188849
2  1.674854 -1.121080  0.712578 -0.037326

# Elements & Parts of a matrix

In [28]:
a1

array([[-1.11079282, -1.58488513,  1.83270074, -0.66310413],
       [ 0.11601061,  1.77481002, -0.98580459,  1.18884926],
       [ 1.67485449, -1.12107986,  0.71257819, -0.03732553]])

In [29]:
a1[1][1]

1.7748100175903578

In [30]:
a1[0:2 , 0:2]

array([[-1.11079282, -1.58488513],
       [ 0.11601061,  1.77481002]])

In [31]:
a1[[0,1] , 0:2]

array([[-1.11079282, -1.58488513],
       [ 0.11601061,  1.77481002]])

In [32]:
a1[[0,1] ,0:2]

array([[-1.11079282, -1.58488513],
       [ 0.11601061,  1.77481002]])

In [33]:
a1

array([[-1.11079282, -1.58488513,  1.83270074, -0.66310413],
       [ 0.11601061,  1.77481002, -0.98580459,  1.18884926],
       [ 1.67485449, -1.12107986,  0.71257819, -0.03732553]])

In [34]:
a1[[1,2],3]
# 1st and 2nd row elements in 3rd column is extracted

array([ 1.18884926, -0.03732553])

# Mathematical Operations on Matrices

In [35]:
m1 = np.random.randint(1,3 , (3,3))

In [36]:
m1

array([[2, 2, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [37]:
m2 = np.random.randint(2,4 , (3,3))

In [38]:
m2

array([[2, 2, 2],
       [3, 3, 3],
       [2, 3, 2]])

In [47]:
# Addition
m1+m2

array([[4, 4, 3],
       [5, 5, 5],
       [4, 5, 4]])

In [39]:
# Elementwise Multiplication
m1*m2

array([[4, 4, 2],
       [6, 6, 6],
       [4, 6, 4]])

In [40]:
# matrix Multiplication
m1@m2

array([[12, 13, 12],
       [14, 16, 14],
       [14, 16, 14]])

In [41]:
m1

array([[2, 2, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [42]:
# Taking power of each element in the matrix
pow(m1 , 4)

array([[16, 16,  1],
       [16, 16, 16],
       [16, 16, 16]], dtype=int32)

In [43]:
# Taking square rootof elemets in a matix
np.sqrt(m1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356]])

In [44]:
# Finding logarithmic of elements in a matrix
np.log10(m1)

array([[0.30103, 0.30103, 0.     ],
       [0.30103, 0.30103, 0.30103],
       [0.30103, 0.30103, 0.30103]])

In [45]:
# Taking exponential of elements in a matrix
np.exp(m1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [46]:
# Taking square of every elemets in matrix
m1**2


array([[4, 4, 1],
       [4, 4, 4],
       [4, 4, 4]], dtype=int32)